# Generated by Django 5.2.3 on 2025-11-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
